#! /bin/bash -x

echo "${1}" > /tmp/debug_filename.txt

riscv32-unknown-elf-gdb -batch \
  -ex "target extended-remote | openocd -c \"gdb_port pipe; log_output openocd.log\" -f \"/home/megan/hifive-arduino/misc/openocd.cfg\" -l /tmp/openocd.log" \
  -ex "monitor load_image ${1}" \
  -ex "set \$pc = 0x80000000" \
  -ex "monitor resume" ${1}

