#! /bin/bash -x

echo "${1}" > /tmp/debug_filename.txt

cp ${1} /home/megan/ARDUINO.elf

openocd -f $CINCO/misc/sifive_hifive.cfg \
	-c "flash protect 0 64 last off; program ${1}; resume 0x20400000; exit" \
	2>&1 | tee openocd_lsketch.log
